### ISSUE TITLE
datadog stackfile for dockercloud

### ISSUE THREAD

**Issue by modius** [tutumcloud/datadog-agent#6]
Not sure what the tutum container offers beyond metadata; here is my stackfile for datadog using their container directly:
```
datadog:
  image: 'datadog/docker-dd-agent:latest'
  deployment_strategy: every_node
  environment:
    - API_KEY=YOURAPIKEYHERE
    - HOSTNAME=$DOCKERCLOUD_NODE_HOSTNAME
  privileged: true
  restart: on-failure
  volumes:
    - '/var/run/docker.sock:/var/run/docker.sock'
    - '/proc:/host/proc:ro'
    - '/sys/fs/cgroup:/host/sys/fs/cgroup:ro'
```

Note the need to use `$DOCKERCLOUD_NODE_HOSTNAME` as the hostname.  Unfortunately this now gives you an `orrible UUID as a node name.
